name: Lint and Format

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linting & Formatting Tools
        run: npm install -g @stoplight/spectral-cli prettier

      - name: Check Formatting (Prettier)
        run: prettier --check openapi.yml postman.json

      - name: Lint OpenAPI Spec (Spectral)
        run: spectral lint openapi.yml
